### ISSUE TITLE
Game Library

### ISSUE THREAD

**Issue by GiovanniDw** [iSirThijs/Gamerdate#4]
This feature will enable the user to Search for games and add them to their own profile

- [x] Retrieve data from the games api
- [x] Create a EJS template for games search/result.
- [x] Render Search results
- [x] When adding a game save to te db if not already there
- [x] Adding the gameID ref to the logged in user
- [x] Showing the users added games on a page to render
- [x] Ability to remove the game from the user

**Comment by iamDistractech** [comment]
I have updated the task list with some additional steps and updated its status. @GiovanniDw could you try to get these in? These features are necessary if we want to pass. If you need help, say so, but try it yourself first. 

You could check my repo for a general pointer, but make sure you don't just copy and paste it, because that would mean I wrote the feature instead of you!: 

https://github.com/iSirThijs/Player2/blob/e1c2c7cc7cda16b9bc3674c5f3da96be2d269ac0/controllers/profile/games.js#L76-L101
https://github.com/iSirThijs/Player2/blob/e1c2c7cc7cda16b9bc3674c5f3da96be2d269ac0/utils/accountUtil.js#L88-L110

**Comment by GiovanniDw** [comment]
Allright I wil start working on this now

**Comment by GiovanniDw** [comment]
The user can now see there added games, and remove them
